"""Setup artifact catalog: which generated files exist for a project.

Pure data+IO helper extracted from scripts/setup-control-plane.py: one entry
per known setup/policy artifact with its policy key, default path, and
existence status.
"""

from __future__ import annotations

import pathlib
from typing import Any

from .config import rel_path

def artifact_status(project_root: pathlib.Path, cfg: dict[str, Any]) -> list[dict[str, Any]]:
    defaults = {
        "project_intake": "seo/project-intake.yaml",
        "project_intake_report": "seo/project-intake-report.md",
        "project_profile": "seo/project-profile.generated.yaml",
        "project_profile_report": "seo/project-profile-report.md",
        "setup_control_plane": "seo/setup/setup-control-plane.md",
        "governance_latest": "seo/setup/latest-governance.json",
        "validation_latest": "seo/setup/latest-validation.txt",
        "active_sources_latest": "seo/setup/latest-sources.json",
        "usage_ledger": "seo/usage/usage-ledger.jsonl",
        "latest_usage_report": "seo/setup/latest-usage-ledger.md",
        "spend_guard_generated": "seo/spend-guard.generated.yaml",
        "spend_guard_report": "seo/setup/spend-guard.md",
        "spend_checklist": "seo/setup/spend-checklist.csv",
        "latest_spend_guard": "seo/setup/latest-spend-guard.md",
        "tool_stack_generated": "seo/tool-stack.generated.yaml",
        "tool_stack_report": "seo/setup/tool-stack-report.md",
        "latest_tool_stack": "seo/setup/latest-tool-stack.md",
        "growth_roadmap_generated": "seo/growth-roadmap.generated.yaml",
        "growth_roadmap_report": "seo/setup/growth-roadmap.md",
        "latest_growth_roadmap": "seo/setup/latest-growth-roadmap.md",
        "onboarding_generated": "seo/onboarding.generated.yaml",
        "onboarding_playbook": "seo/setup/onboarding-playbook.md",
        "onboarding_checklist": "seo/setup/onboarding-checklist.csv",
        "latest_onboarding_playbook": "seo/setup/latest-onboarding-playbook.md",
        "setup_blueprint_generated": "seo/setup-blueprint.generated.yaml",
        "setup_blueprint": "seo/setup/setup-blueprint.md",
        "setup_blueprint_json": "seo/setup/setup-blueprint.json",
        "setup_matrix_csv": "seo/setup/setup-matrix.csv",
        "latest_setup_blueprint": "seo/setup/latest-setup-blueprint.md",
        "upgrade_assistant": "seo/setup/upgrade-assistant.md",
        "upgrade_assistant_json": "seo/setup/upgrade-assistant.json",
        "upgrade_questionnaire_csv": "seo/setup/upgrade-questionnaire.csv",
        "latest_upgrade_assistant": "seo/setup/latest-upgrade-assistant.md",
        "project_upgrade_apply_report": "seo/setup/project-upgrade-apply.md",
        "project_upgrade_apply_json": "seo/setup/project-upgrade-apply.json",
        "project_upgrade_apply_csv": "seo/setup/project-upgrade-apply.csv",
        "latest_project_upgrade_apply": "seo/setup/latest-project-upgrade-apply.md",
        "latest_project_upgrade_apply_json": "seo/setup/latest-project-upgrade-apply.json",
        "access_key_assistant": "seo/setup/access-key-assistant.md",
        "access_key_assistant_json": "seo/setup/access-key-assistant.json",
        "access_key_assistant_csv": "seo/setup/access-key-assistant.csv",
        "latest_access_key_assistant": "seo/setup/latest-access-key-assistant.md",
        "launch_plan_generated": "seo/launch-plan.generated.yaml",
        "launch_plan_report": "seo/setup/launch-plan.md",
        "launch_checklist": "seo/setup/launch-checklist.csv",
        "latest_launch_plan": "seo/setup/latest-launch-plan.md",
        "project_journey_report": "seo/setup/project-journey.md",
        "project_journey_json": "seo/setup/project-journey.json",
        "project_journey_checklist": "seo/setup/project-journey-checklist.csv",
        "latest_project_journey": "seo/setup/latest-project-journey.md",
        "latest_project_journey_json": "seo/setup/latest-project-journey.json",
        "research_package_quality_report": "seo/research-package/research-package-quality.md",
        "research_package_quality_json": "seo/research-package/research-package-quality.json",
        "research_package_action_plan": "seo/research-package/research-package-action-plan.md",
        "semantic_core_cleaned": "seo/research-package/semantic-core.cleaned.csv",
        "semantic_core_rejected": "seo/research-package/semantic-core.rejected.csv",
        "semantic_core_resynced": "seo/research-package/semantic-core.resynced.csv",
        "google_nlp_entity_coverage": "seo/research-package/entity_coverage.jsonl",
        "orphan_url_backlog": "seo/research-package/content-plan.orphan-backlog.csv",
        "serp_validation_plan": "seo/research-package/serp-validation-plan.csv",
        "serp_validation_import_report": "seo/research-package/serp-validation-import.md",
        "serp_validation_import_json": "seo/research-package/serp-validation-import.json",
        "spoke_opportunities": "seo/research-package/spoke-opportunities.csv",
        "research_package_repair_report": "seo/research-package/research-package-repair.md",
        "research_package_repair_json": "seo/research-package/research-package-repair.json",
        "entity_graph_quality_report": "seo/research-package/entity-graph-quality.md",
        "entity_graph_quality_json": "seo/research-package/entity-graph-quality.json",
        "page_outlines_v3_dir": "seo/research-package/page-outlines-v3",
        "copywriter_ready_dir": "seo/research-package/copywriter-ready",
        "page_outline_triplets": "seo/research-package/vector/page_outline_triplets.jsonl",
        "page_outline_quality_report": "seo/research-package/page-outline-quality.md",
        "page_outline_quality_json": "seo/research-package/page-outline-quality.json",
        "latest_page_outline_quality": "seo/research-package/latest-page-outline-quality.md",
        "latest_page_outline_quality_json": "seo/research-package/latest-page-outline-quality.json",
        "content_drafts_dir": "seo/research-package/drafts",
        "knowledge_wiki_root": "seo/knowledge/wiki",
        "knowledge_obsidian_root": "seo/knowledge/obsidian-vault",
        "knowledge_graph_corpus": "seo/knowledge/graph-corpus",
        "knowledge_graph_root": "seo/knowledge/graph",
        "knowledge_hybrid_index_root": "seo/knowledge/zvec",
        "knowledge_project_manifest": "seo/knowledge/wiki/project-manifest.json",
        "knowledge_state_summary": "seo/knowledge/wiki/state/latest-summary.md",
        "knowledge_context_dir": "seo/knowledge/wiki/context",
        "knowledge_latest_context_pack": "seo/knowledge/wiki/context/latest-context-pack.md",
        "knowledge_latest_context_pack_json": "seo/knowledge/wiki/context/latest-context-pack.json",
        "knowledge_content_taste_report": "seo/knowledge/wiki/reports/content-taste-gate.md",
        "knowledge_content_taste_json": "seo/knowledge/wiki/reports/content-taste-gate.json",
        "knowledge_wiki_preflight_report": "seo/knowledge/wiki/preflight/wiki-preflight.md",
        "knowledge_wiki_preflight_json": "seo/knowledge/wiki/preflight/wiki-preflight.json",
        "knowledge_review_cluster_plan": "seo/knowledge/wiki/frameworks/review-cluster-plan.md",
        "knowledge_review_cluster_json": "seo/knowledge/wiki/frameworks/review-clusters.json",
        "knowledge_api_catalog": "seo/knowledge/wiki/api-catalog/api-catalog.json",
        "knowledge_api_candidates": "seo/knowledge/wiki/api-catalog/api-candidates.jsonl",
        "knowledge_decision_log": "seo/knowledge/wiki/decisions/decision-log.jsonl",
        "knowledge_graphify_status": "seo/knowledge/graph/graphify-status.json",
        "knowledge_graphify_local_graph": "seo/knowledge/graph/graphify-local-graph.json",
        "knowledge_zvec_status": "seo/knowledge/zvec/zvec-status.json",
        "knowledge_zvec_db": "seo/knowledge/zvec/hybrid.sqlite",
        "context_pack_report": "seo/setup/context-pack.md",
        "context_pack_json": "seo/setup/context-pack.json",
        "latest_context_pack": "seo/setup/latest-context-pack.md",
        "token_waste_audit_report": "seo/setup/token-waste-audit.md",
        "token_waste_audit_json": "seo/setup/token-waste-audit.json",
        "latest_token_waste_audit": "seo/setup/latest-token-waste-audit.md",
        "latest_token_waste_audit_json": "seo/setup/latest-token-waste-audit.json",
        "perplexity_health_report": "seo/setup/perplexity-health.md",
        "perplexity_health_json": "seo/setup/perplexity-health.json",
        "latest_perplexity_health": "seo/setup/latest-perplexity-health.md",
        "latest_perplexity_health_json": "seo/setup/latest-perplexity-health.json",
        "notebooklm_health_report": "seo/setup/notebooklm-health.md",
        "notebooklm_health_json": "seo/setup/notebooklm-health.json",
        "latest_notebooklm_health": "seo/setup/latest-notebooklm-health.md",
        "latest_notebooklm_health_json": "seo/setup/latest-notebooklm-health.json",
        "xmlriver_health_report": "seo/setup/xmlriver-health.md",
        "xmlriver_health_json": "seo/setup/xmlriver-health.json",
        "latest_xmlriver_health": "seo/setup/latest-xmlriver-health.md",
        "latest_xmlriver_health_json": "seo/setup/latest-xmlriver-health.json",
        "writerzen_health_report": "seo/setup/writerzen-health.md",
        "writerzen_health_json": "seo/setup/writerzen-health.json",
        "latest_writerzen_health": "seo/setup/latest-writerzen-health.md",
        "latest_writerzen_health_json": "seo/setup/latest-writerzen-health.json",
        "setup_gap_audit_report": "seo/setup/setup-gap-audit.md",
        "setup_gap_audit_json": "seo/setup/setup-gap-audit.json",
        "latest_setup_gap_audit": "seo/setup/latest-setup-gap-audit.md",
        "setup_questionnaire": "seo/setup/setup-questionnaire.md",
        "setup_questionnaire_csv": "seo/setup/setup-questionnaire.csv",
        "latest_setup_questionnaire": "seo/setup/latest-setup-questionnaire.md",
        "setup_answer_plan": "seo/setup/setup-answer-plan.md",
        "setup_answer_plan_json": "seo/setup/setup-answer-plan.json",
        "latest_setup_answer_plan": "seo/setup/latest-setup-answer-plan.md",
        "automation_recommendations": "seo/automations/automation-recommendations.md",
        "automation_policy_generated": "seo/automation-policy.generated.yaml",
        "automation_plan": "seo/automations/automation-plan.md",
        "automation_plan_json": "seo/automations/automation-plan.json",
        "automation_crontab": "seo/automations/crontab.txt",
        "latest_task_route": "seo/setup/latest-task-route.md",
        "ai_brand_audit_report": "seo/vnext/ai-brand-audit.md",
        "answer_units_audit_report": "seo/vnext/answer-units-audit.md",
        "ai_bot_access_check_report": "seo/vnext/ai-bot-access-check.md",
        "technical_guardrails_audit_report": "seo/vnext/technical-guardrails-audit.md",
        "expert_source_pack_report": "seo/vnext/expert-source-pack.md",
        "technical_site_audit_report": "seo/technical/technical-site-audit.md",
        "link_audit_report": "seo/technical/link-audit.md",
        "redirect_map_audit_report": "seo/technical/redirect-map-audit.md",
        "lighthouse_audit_report": "seo/technical/lighthouse-audit.md",
        "gsc_url_inspection_report": "seo/technical/gsc-url-inspection.md",
        "gsc_indexing_export_report": "seo/technical/gsc-indexing-export.md",
        "gsc_indexing_queue_report": "seo/technical/gsc-indexing-queue.md",
        "gsc_indexing_submit_report": "seo/technical/gsc-indexing-submit.md",
        "gsc_indexing_recheck_report": "seo/technical/gsc-indexing-recheck.md",
        "indexnow_submit_report": "seo/technical/indexnow-submit.md",
        "yandex_recrawl_submit_report": "seo/technical/yandex-recrawl-submit.md",
        "yandex_recrawl_status_report": "seo/technical/yandex-recrawl-status.md",
        "bing_url_inspection_report": "seo/technical/bing-url-inspection.md",
        "serpstat_audit_report": "seo/technical/serpstat-audit.md",
        "labrika_source_pack_report": "seo/technical/labrika-source-pack.md",
        "labrika_health_report": "seo/technical/labrika-health.md",
        "technical_mcp_health_report": "seo/technical/technical-mcp-health.md",
    }
    policy_files = cfg.get("policy_files", {}) if isinstance(cfg.get("policy_files"), dict) else {}
    rows = []
    for key, default in defaults.items():
        raw_path = policy_files.get(key, default) if key in policy_files else default
        path = rel_path(project_root, raw_path)
        rows.append({"key": key, "path": raw_path, "exists": path.exists()})
    return rows
