"""Static tool catalog and decision order for tool-stack-recommender.

Pure data: tool ids with labels, categories, costs, actions, and default
reasons. Keeping it here halves the recommender script and lets other
scripts (access-key assistant, setup control plane) import the same catalog.
"""

from __future__ import annotations

from typing import Any

DECISION_ORDER = ["enabled", "report_only", "approval_required", "disabled", "not_applicable"]

TOOL_CATALOG: dict[str, dict[str, Any]] = {
    # Site and public technical checks.
    "robots_sitemap": {
        "label": "Robots, sitemap, canonicals",
        "category": "technical",
        "cost": "free",
        "actions": ["robots_sitemap_check", "canonical_noindex_audit", "sitemap_coverage_diff"],
        "default_reason": "Free public technical checks; keep enabled for every project.",
    },
    "schema_crawl": {
        "label": "Schema crawl and validation",
        "category": "technical",
        "cost": "free",
        "actions": ["schema_detect", "schema_validate", "entity_graph_diff"],
        "default_reason": "Free local crawl/parser layer for Product, Organization, LocalBusiness, FAQ, Article schema.",
    },
    "pagespeed_crux": {
        "label": "PageSpeed Insights / CrUX",
        "category": "quality",
        "cost": "free_or_quota",
        "source": "pagespeed_insights",
        "actions": ["pagespeed_check", "core_web_vitals_report"],
        "default_reason": "Free site quality data; API key is optional and can stay unset.",
    },

    # Yandex.
    "yandex_webmaster": {
        "label": "Yandex Webmaster",
        "category": "search_console",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "engines": ["yandex"],
        "cost": "free",
        "source": "yandex_webmaster_history",
        "env": ["YANDEX_OAUTH_TOKEN", "YANDEX_USER_ID", "YANDEX_WEBMASTER_HOST_ID"],
        "actions": ["index_status", "crawl_errors", "sitemap_status", "search_queries"],
        "default_reason": "Primary free index and query data source for Yandex/RU projects.",
    },
    "yandex_wordstat": {
        "label": "Yandex Wordstat",
        "category": "keyword_research",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "engines": ["yandex"],
        "cost": "free_or_manual",
        "source": "yandex_wordstat",
        "actions": ["keyword_demand", "seasonality", "commercial_modifier_expansion"],
        "default_reason": "Primary RU/Yandex demand source.",
    },
    "yandex_wordstat_deep": {
        "label": "Yandex Wordstat deep",
        "category": "keyword_research",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "engines": ["yandex"],
        "cost": "free_or_manual",
        "source": "yandex_wordstat_deep",
        "actions": ["right_column_expansion", "seasonality_deep_dive"],
        "default_reason": "Useful for RU keyword tails; browser/manual collection only.",
    },
    "yandex_suggest": {
        "label": "Yandex Suggest",
        "category": "keyword_research",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "engines": ["yandex"],
        "cost": "free",
        "source": "yandex_suggest",
        "actions": ["suggest_harvest", "query_patterns"],
        "default_reason": "Free Yandex query-tail source.",
    },
    "yandex_serp_blocks": {
        "label": "Yandex SERP blocks",
        "category": "serp",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "engines": ["yandex"],
        "cost": "free_or_manual",
        "source": "yandex_serp_blocks",
        "actions": ["serp_features", "paa_like_blocks", "competitor_patterns"],
        "default_reason": "Free SERP evidence for Yandex-specific blocks.",
    },
    "yandex_images_suggest": {
        "label": "Yandex Images suggest",
        "category": "image_seo",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "engines": ["yandex"],
        "cost": "free_or_manual",
        "source": "yandex_images_suggest",
        "actions": ["image_query_patterns", "alt_text_gap"],
        "default_reason": "Free image-search demand hints for RU projects.",
    },
    "yandex_q": {
        "label": "Yandex Q / answer surfaces",
        "category": "ai_visibility",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "engines": ["yandex"],
        "cost": "free_or_manual",
        "source": "yandex_q",
        "actions": ["question_patterns", "faq_gap"],
        "default_reason": "Free question evidence for FAQ/AEO work in Yandex contexts.",
    },
    "yandex_business_maps": {
        "label": "Yandex Business / Maps",
        "category": "local_seo",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "project_types": ["local_business", "ecommerce", "corporate"],
        "requires_local": True,
        "cost": "free_or_cabinet",
        "source": "yandex_business_maps",
        "actions": ["nap_check", "map_profile_quality", "review_velocity"],
        "default_reason": "Use when the project has a real office/store/warehouse shown to users.",
    },
    "yandex_merchant": {
        "label": "Yandex Merchant / Товары",
        "category": "merchant",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "project_types": ["ecommerce"],
        "requires_ecommerce": True,
        "cost": "free_or_cabinet",
        "source": "yandex_merchant",
        "env": ["YANDEX_MERCHANT_BUSINESS_ID"],
        "actions": ["feed_errors", "product_quality", "offer_visibility"],
        "default_reason": "Useful for RU ecommerce feeds/products; no ad spend required.",
    },
    "yandex_metrika": {
        "label": "Yandex Metrica",
        "category": "analytics",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "cost": "free_tracking",
        "tracking_tag": True,
        "env": ["YANDEX_OAUTH_TOKEN", "YANDEX_METRIKA_COUNTER_ID"],
        "actions": ["traffic_report", "goals", "ecommerce_events"],
        "default_reason": "Analytics tag requires project legal/tracking policy approval before installation.",
    },
    "yandex_direct": {
        "label": "Yandex Direct",
        "category": "ads",
        "ecosystem": "yandex",
        "countries": ["RU"],
        "cost": "ads_spend",
        "ads": True,
        "actions": ["keyword_planning", "campaign_audit", "negative_keywords"],
        "default_reason": "Useful for planning/audits; campaign launch/spend always requires approval.",
    },

    # Google.
    "google_search_console": {
        "label": "Google Search Console",
        "category": "search_console",
        "ecosystem": "google",
        "engines": ["google"],
        "cost": "free",
        "source": "google_search_console",
        "env": ["GOOGLE_APPLICATION_CREDENTIALS", "GSC_SITE_URL"],
        "actions": ["queries", "index_coverage", "sitemaps", "ctr_pages"],
        "default_reason": "Free read-only Google index and query evidence; no site tracking tag.",
    },
    "google_trends": {
        "label": "Google Trends",
        "category": "keyword_research",
        "ecosystem": "google",
        "engines": ["google"],
        "cost": "free",
        "source": "google_trends",
        "actions": ["seasonality", "rising_queries", "topic_interest"],
        "default_reason": "Free Google demand trend source.",
    },
    "google_suggest": {
        "label": "Google Suggest",
        "category": "keyword_research",
        "ecosystem": "google",
        "engines": ["google"],
        "cost": "free",
        "source": "google_suggest",
        "actions": ["suggest_harvest", "query_patterns"],
        "default_reason": "Free query-tail source for Google markets.",
    },
    "google_cloud_nlp": {
        "label": "Google Cloud Natural Language",
        "category": "entity_nlp",
        "ecosystem": "google",
        "cost": "free_quota_then_paid",
        "source": "google_cloud_nlp",
        "env": ["GOOGLE_APPLICATION_CREDENTIALS"],
        "policy": "google_nlp_policy",
        "billing_required": True,
        "actions": ["entity_analysis", "content_classification", "syntax", "moderation_guarded"],
        "default_reason": "Entity audit layer only; uses cache and important URL selection, not a ranking signal.",
    },
    "google_merchant": {
        "label": "Google Merchant Center",
        "category": "merchant",
        "ecosystem": "google",
        "engines": ["google"],
        "project_types": ["ecommerce"],
        "requires_ecommerce": True,
        "cost": "free_or_cabinet",
        "source": "google_merchant",
        "env": ["GOOGLE_APPLICATION_CREDENTIALS", "GOOGLE_MERCHANT_ACCOUNT_ID"],
        "actions": ["feed_errors", "product_quality", "free_listings"],
        "default_reason": "Useful for ecommerce product/feed quality; ads are separate and approval-gated.",
    },
    "google_business_profile": {
        "label": "Google Business Profile",
        "category": "local_seo",
        "ecosystem": "google",
        "engines": ["google"],
        "project_types": ["local_business", "ecommerce", "corporate"],
        "requires_local": True,
        "cost": "free_or_cabinet",
        "source": "google_business_profile",
        "env": ["GOOGLE_APPLICATION_CREDENTIALS", "GOOGLE_BUSINESS_ACCOUNT_ID", "GOOGLE_BUSINESS_LOCATION_ID"],
        "actions": ["nap_check", "map_profile_quality", "reviews"],
        "default_reason": "Useful when the project has a real public local profile; no analytics tag required.",
    },
    "google_analytics_4": {
        "label": "Google Analytics 4",
        "category": "analytics",
        "ecosystem": "google",
        "cost": "free_tracking",
        "tracking_tag": True,
        "env": ["GOOGLE_APPLICATION_CREDENTIALS", "GA4_PROPERTY_ID"],
        "actions": ["traffic_report", "events", "ecommerce_events"],
        "default_reason": "Requires tracking/legal approval; for RF projects keep disabled unless policy explicitly allows it.",
    },
    "google_ads": {
        "label": "Google Ads",
        "category": "ads",
        "ecosystem": "google",
        "cost": "ads_spend",
        "ads": True,
        "actions": ["keyword_planner", "search_terms", "campaign_audit"],
        "default_reason": "Planning/audit only by default; launch/spend requires approval and budget.",
    },
    "google_youtube": {
        "label": "YouTube Data API",
        "category": "video_seo",
        "ecosystem": "google",
        "cost": "free_quota",
        "env": ["GOOGLE_APPLICATION_CREDENTIALS", "YOUTUBE_CHANNEL_ID"],
        "actions": ["video_inventory", "title_description_audit", "publish_if_approved"],
        "default_reason": "Useful for video SEO and channel inventory; publishing requires separate approval.",
    },

    # Bing / Microsoft.
    "bing_webmaster": {
        "label": "Bing Webmaster Tools",
        "category": "search_console",
        "ecosystem": "microsoft",
        "engines": ["bing"],
        "cost": "free",
        "source": "bing_webmaster",
        "env": ["BING_WEBMASTER_API_KEY", "BING_SITE_URL"],
        "actions": ["index_status", "crawl_errors", "keywords", "backlinks"],
        "default_reason": "Free read-only Bing/Copilot-facing search console.",
    },
    "indexnow": {
        "label": "IndexNow",
        "category": "index_submission",
        "ecosystem": "microsoft",
        "engines": ["bing", "yandex"],
        "cost": "free_mutating",
        "source": "indexnow",
        "env": ["INDEXNOW_KEY", "INDEXNOW_KEY_LOCATION"],
        "mutating": True,
        "actions": ["submit_changed_urls"],
        "default_reason": "Free URL submission, but mutates search-engine queues; approval-gated.",
    },
    "bing_places": {
        "label": "Bing Places",
        "category": "local_seo",
        "ecosystem": "microsoft",
        "engines": ["bing"],
        "project_types": ["local_business", "ecommerce", "corporate"],
        "requires_local": True,
        "cost": "free_or_cabinet",
        "source": "bing_places",
        "actions": ["nap_check", "business_profile_quality", "reviews"],
        "default_reason": "Useful for local SEO and Bing/Copilot; usually managed through the cabinet.",
    },
    "microsoft_clarity": {
        "label": "Microsoft Clarity",
        "category": "analytics",
        "ecosystem": "microsoft",
        "cost": "free_tracking",
        "tracking_tag": True,
        "actions": ["session_recordings", "heatmaps"],
        "default_reason": "Tracking/recording tag requires legal approval; keep disabled for RF projects by default.",
    },
    "microsoft_ads": {
        "label": "Microsoft Ads",
        "category": "ads",
        "ecosystem": "microsoft",
        "cost": "ads_spend",
        "ads": True,
        "actions": ["keyword_planning", "campaign_audit"],
        "default_reason": "Often requires billing; skip launch/spend unless explicitly approved.",
    },

    # Paid/quota SEO tools and AI layers.
    "neuronwriter": {
        "label": "NeuronWriter",
        "category": "content_nlp",
        "cost": "subscription_quota",
        "source": "neuronwriter",
        "env": ["NEURON_API_KEY"],
        "policy": "neuronwriter_limits",
        "actions": ["serp_content_editor", "competitor_terms", "content_score", "plagiarism_gate"],
        "default_reason": "Use high-plan limits for important pages only; cache/export results, avoid whole-catalog runs.",
    },
    "writerzen": {
        "label": "WriterZen",
        "category": "keyword_research",
        "cost": "subscription_quota",
        "source": "writerzen",
        "actions": [
            "topic_discovery",
            "keyword_explorer",
            "keyword_planner",
            "intent_and_buying_journey",
            "serp_type",
            "allintitle_kgr",
            "domain_focus",
            "browser_export_ingestion",
        ],
        "default_reason": "Useful subscription/browser source for Google keyword expansion, clusters, intent, Buying Journey, SERP Type, Allintitle/KGR and Domain Focus. No public API is assumed; use logged-in browser exports and distillates.",
    },
    "keyso": {
        "label": "Keys.so",
        "category": "keyword_research",
        "ecosystem": "keyso",
        "countries": ["RU"],
        "cost": "subscription_quota",
        "source": "keyso",
        "env": ["KEYSO_API_TOKEN"],
        "actions": ["wordstat_frequency", "visibility", "lost_keywords", "competitors"],
        "default_reason": "Strong RU/Yandex evidence source; use with request caps and cache.",
    },
    "serpstat": {
        "label": "Serpstat",
        "category": "keyword_research",
        "cost": "subscription_quota",
        "source": "serpstat",
        "env": ["SERPSTAT_API_KEY"],
        "actions": ["volume", "kd", "competitor_gap"],
        "default_reason": "Useful quota-based Google market evidence; use with credit guards.",
    },
    "dataforseo": {
        "label": "DataForSEO",
        "category": "serp_api",
        "cost": "paid_api",
        "source": "dataforseo",
        "actions": ["serp_api", "rank_checks", "keyword_data"],
        "default_reason": "Powerful but paid; only run with monthly cap and explicit approval.",
    },
    "xmlriver": {
        "label": "XMLRiver",
        "category": "serp_api",
        "ecosystem": "xmlriver",
        "engines": ["google", "yandex"],
        "cost": "paid_api",
        "source": "xmlriver",
        "env": ["XMLRIVER_USER_ID", "XMLRIVER_API_KEY"],
        "actions": [
            "google_serp_blocks",
            "yandex_serp_blocks",
            "wordstat_new",
            "ads_blocks",
            "shopping_prices",
            "maps",
            "suggest",
            "ai_overview_blocks",
            "indexation_checks",
        ],
        "default_reason": "Cheap guarded SERP/Wordstat enrichment for Google/Yandex blocks; run only with cache, budget guard and explicit paid API approval.",
    },
    "spyfu": {
        "label": "SpyFu",
        "category": "competitor_research",
        "countries_exclude": ["RU"],
        "cost": "subscription_quota",
        "source": "spyfu",
        "actions": ["competitor_keywords", "ppc_history"],
        "default_reason": "Useful for US/UK/EU competitor/PPC data; not useful for RU/Yandex.",
    },
    "answerthepublic": {
        "label": "AnswerThePublic",
        "category": "question_research",
        "cost": "subscription_quota",
        "source": "answerthepublic",
        "env": ["TOKEN_ANSWERTHEPUBLIC"],
        "actions": ["question_templates", "prepositions", "comparisons"],
        "default_reason": "Use selectively; RU projects use EN/US templates with translation if needed.",
    },
    "perplexity": {
        "label": "Perplexity",
        "category": "ai_visibility",
        "cost": "subscription_or_paid",
        "source": "perplexity",
        "actions": ["citation_checks", "answer_visibility", "competitor_mentions"],
        "default_reason": "Useful for AI answer visibility and fact checks; browser/subscription gated.",
    },
    "llm_cli": {
        "label": "LLM CLI distillates",
        "category": "ai_visibility",
        "cost": "llm_tokens",
        "source": "llm_cli",
        "actions": ["semantic_distillates", "ai_visibility_prompts", "content_gap_synthesis"],
        "default_reason": "Use only distilled prompts/results; raw collection stays on disk.",
    },
    "openai_chatgpt": {
        "label": "OpenAI / ChatGPT",
        "category": "ai_visibility",
        "cost": "llm_tokens",
        "actions": ["ai_visibility_checks", "content_synthesis", "entity_gap_synthesis"],
        "default_reason": "Useful for AI visibility simulations; token spend must follow ledger caps.",
    },
    "claude": {
        "label": "Claude",
        "category": "ai_visibility",
        "cost": "llm_tokens",
        "actions": ["content_review", "structured_rewrite", "evidence_synthesis"],
        "default_reason": "Useful as reasoning/review layer; token spend must follow ledger caps.",
    },
    "gemini": {
        "label": "Gemini API",
        "category": "ai_visibility",
        "ecosystem": "google",
        "cost": "llm_tokens",
        "env": ["GEMINI_API_KEY"],
        "actions": ["ai_visibility_checks", "multimodal_review", "content_synthesis"],
        "default_reason": "Optional Google AI layer; needs its own key/quota guard.",
    },
    "deepseek": {
        "label": "DeepSeek",
        "category": "ai_visibility",
        "cost": "llm_tokens",
        "env": ["DEEPSEEK_API_KEY"],
        "actions": ["content_synthesis", "semantic_checks"],
        "default_reason": "Optional AI comparison layer; token spend must be ledgered.",
    },
    "robots_ai_content_signals": {
        "label": "Robots AI Content Signals",
        "category": "ai_policy",
        "cost": "free",
        "actions": ["content_signal_audit", "robots_rules_review"],
        "default_reason": "Audit Content-Signal rules such as search=yes, ai-input=yes, ai-train=no; do not change robots automatically.",
    },
}
