#!/usr/bin/env python3
"""T-089 round 2 — the static half of finding C's fix.

`seo_cycle_core.spend_guard`'s runtime gate (PAID_HOSTS + armed_spend())
stops a call to an ALREADY-REGISTERED paid host. It cannot, by construction,
stop a call to a host nobody has told it about yet — that is not a bug to
patch, it is what "the gate lives on data, not on omniscience" means (see
`spend_guard.py`'s module docstring for the full, honest statement of what
the runtime check does and does not guarantee).

This test is the other half: a closed-world inventory. It scans every
`http(s)://` literal in `scripts/*.py` and requires EVERY hostname found —
paid or free — to be consciously sorted into `spend_guard.PAID_HOSTS` or
`FREE_HOSTS` below. A brand-new script hitting a brand-new host fails THIS
test at review/CI time, by name, with the file and host named in the
failure message — it does not need someone to notice a missing gate at
runtime, and it does not need the new host to already be known.

This is deliberately not clever: a regex over string literals, not an AST
walk with control-flow analysis, and it flags a URL mentioned in a
docstring or comment exactly like one used in a real call site (over-count,
not under-count — a host in a comment just needs classifying once too,
same as a real one; it is never silently skipped). That is the honest
trade of a static safety net: it cannot verify a call actually happens, but
it cannot let an unclassified host pass unnoticed either.
"""

from __future__ import annotations

import pathlib
import re
import sys
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
sys.path.insert(0, str(SCRIPTS))

from seo_cycle_core.spend_guard import PAID_HOSTS  # noqa: E402

_URL_RE = re.compile(r"https?://([A-Za-z0-9_.\-]+)", re.IGNORECASE)

# Every non-paid host any script in this repo mentions, as of this ticket —
# generated by the exact same scan this test performs
# (`grep -rhoE 'https?://[A-Za-z0-9_.-]+' scripts --include='*.py'`) and
# reviewed by hand. A new entry here is a one-line, low-risk change; a
# missing one fails this test by name, it does not fail silently.
FREE_HOSTS = frozenset({
    "...",  # regex artifact from a "https://...example.com" placeholder in a docstring
    "site", "site.ru",  # placeholder hosts in usage examples/docs
    "localhost", "example.com",
    "about.you.com", "accounts.google.com", "ahrefs.com", "aistudio.google.com",
    "analytics.google.com", "answerthepublic.com", "api-metrika.yandex.net",
    "api.answerthepublic.com", "api.indexnow.org", "api.serpstat.com", "api.slack.com",
    "api.telegram.org", "api.tildacdn.info", "api.webmaster.yandex.net",
    "app.neuronwriter.com", "app.writerzen.net", "bot.sidetrade.com", "business.google.com",
    "cohere.com", "commoncrawl.org", "console.cloud.google.com", "dataforseo.com",
    "dev.2gis.ru", "developer.amazon.com", "developers.facebook.com", "developers.google.com",
    "direct.yandex.ru", "duckduckgo.com", "github.com", "iask.com", "journal.topvisor.com",
    "keys.so", "kokoc.com", "labrika.com", "learn.microsoft.com", "merchants.google.com",
    "merchants.yandex.ru", "mj12bot.com", "mybusiness.googleapis.com",
    "mybusinessbusinessinformation.googleapis.com", "naver.me", "neeva.com",
    "neuronwriter.com", "notebooklm.google.com", "oauth.yandex.ru", "oauth2.googleapis.com",
    "omgili.com", "openai.com", "opensiteexplorer.org", "perplexity.ai", "pifagor.ai",
    "platform.deepseek.com", "pr-cy.ru", "raw.githubusercontent.com", "schema.org",
    "scrapy.org", "search.google.com", "searchconsole.googleapis.com", "seo-agents.io",
    "serpstat.com", "shoppingcontent.googleapis.com", "ssl.bing.com", "suggest.yandex.ru",
    "suggestqueries.google.com", "support.google.com", "t.me", "tagmanager.googleapis.com",
    "tilda.cc", "ucri.nict.go.jp", "velen.io", "webmaster.petalsearch.com",
    "webmaster.yandex.ru", "webmeup-crawler.com", "webz.io", "www.allenai.org",
    "www.anthropic.com", "www.apple.com", "www.archive.org", "www.baidu.com",
    "www.bing.com", "www.brightedge.com", "www.diffbot.com", "www.exabot.com",
    "www.google.com", "www.googleapis.com", "www.grapeshot.co.uk", "www.indexnow.org",
    "www.keyso.so", "www.linkedin.com", "www.perplexity.ai", "www.pinterest.com",
    "www.qwant.com", "www.semrush.com", "www.sentibot.eu", "www.sitemaps.org",
    "www.sogou.com", "www.timpi.io", "www.turnitin.com", "x.ai", "xmlriver.com",
    "yandex.com", "yandex.ru",
})


def _scan_hosts() -> dict[str, set[str]]:
    """host -> set of relative file paths mentioning it."""
    found: dict[str, set[str]] = {}
    for path in sorted(SCRIPTS.rglob("*.py")):
        text = path.read_text(encoding="utf-8", errors="replace")
        for match in _URL_RE.finditer(text):
            raw = match.group(1).lower()
            host = raw.rstrip(".") or raw  # "..." placeholder rstrips to "" — keep it as-is
            found.setdefault(host, set()).add(str(path.relative_to(ROOT)))
    return found


class ClosedWorldHostsTest(unittest.TestCase):
    def test_registries_do_not_overlap(self) -> None:
        overlap = PAID_HOSTS & FREE_HOSTS
        self.assertFalse(overlap, f"хосты не могут быть одновременно платными и свободными: {overlap}")

    def test_every_host_mentioned_in_scripts_is_classified(self) -> None:
        found = _scan_hosts()
        known = PAID_HOSTS | FREE_HOSTS
        unclassified = {host: files for host, files in found.items() if host not in known}
        if unclassified:
            lines = [f"  {host}: {sorted(files)}" for host, files in sorted(unclassified.items())]
            self.fail(
                "Найдены хосты, не отнесённые ни к PAID_HOSTS "
                "(scripts/seo_cycle_core/spend_guard.py), ни к FREE_HOSTS "
                "(этот файл) — classify them (add to whichever registry is correct):\n"
                + "\n".join(lines)
            )

    def test_all_registered_paid_hosts_are_still_mentioned_somewhere(self) -> None:
        """Symmetric sanity check: a PAID_HOSTS entry nobody's code actually
        contacts anymore is dead weight worth noticing, not silently kept
        forever (not a correctness requirement — informational)."""
        found = _scan_hosts()
        stale = PAID_HOSTS - set(found)
        # Informational only: fail loudly enough to be seen, but this is not
        # a security property, so keep it a plain assertion the way any
        # other "keep the registry tidy" check would be.
        self.assertFalse(stale, f"PAID_HOSTS содержит хосты, которых больше нет в scripts/: {stale} "
                                f"(не баг безопасности — но лишний список гниёт молча, если не смотреть)")

    def test_scan_actually_finds_something(self) -> None:
        """Positive control: the regex itself must be capable of finding a
        host — a scanner that always returns empty would make every test
        above vacuously pass."""
        found = _scan_hosts()
        self.assertIn("api.dataforseo.com", found)
        self.assertGreater(len(found), 50)


if __name__ == "__main__":
    unittest.main()
