#!/usr/bin/env python3
"""Generate project-local MCP configuration without storing secrets."""

from __future__ import annotations

import argparse
import json
import pathlib
import sys
from typing import Any

from seo_cycle_core.config import find_config, load_yaml, nested_get, project_root_for, write_text


BEGIN = "# BEGIN seo-cycle managed project MCP"
END = "# END seo-cycle managed project MCP"
DEFAULT_SERVER_NAME = "novamira-wordpress"
DEFAULT_PACKAGE = "@automattic/mcp-wordpress-remote@latest"
WORDPRESS_MCP_ENV = (
    "WP_API_URL",
    "WP_API_USERNAME",
    "WP_API_PASSWORD",
)


def is_wordpress_project(cfg: dict[str, Any]) -> bool:
    cms = (nested_get(cfg, "publishing.cms") or cfg.get("cms") or "").strip().lower()
    return cms == "wordpress"


def shell_script(project_root: pathlib.Path) -> str:
    root = str(project_root)
    return (
        f"cd {shell_quote(root)} && "
        "set -a; [ -f .env ] && . ./.env; set +a; "
        ': "${WP_API_URL:?WP_API_URL missing in project .env}"; '
        ': "${WP_API_USERNAME:?WP_API_USERNAME missing in project .env}"; '
        ': "${WP_API_PASSWORD:?WP_API_PASSWORD missing in project .env}"; '
        f"exec npx -y {DEFAULT_PACKAGE}"
    )


def shell_quote(value: str) -> str:
    return "'" + value.replace("'", "'\"'\"'") + "'"


def toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def managed_block(project_root: pathlib.Path, server_name: str) -> str:
    command = shell_script(project_root)
    lines = [
        BEGIN,
        "# Project-local MCP config generated by seo-cycle.",
        "# Secrets are read from this project's .env at MCP startup.",
        f"[mcp_servers.{server_name}]",
        'command = "bash"',
        f"args = [\"-lc\", {toml_string(command)}]",
        "startup_timeout_sec = 30",
        "tool_timeout_sec = 180",
        "",
        f"[mcp_servers.{server_name}.env]",
        'SEO_CYCLE_PROJECT_MCP = "true"',
        END,
        "",
    ]
    return "\n".join(lines)


def replace_managed_block(existing: str, block: str) -> str:
    if BEGIN in existing and END in existing:
        before, rest = existing.split(BEGIN, 1)
        _, after = rest.split(END, 1)
        return before.rstrip() + "\n\n" + block.rstrip() + "\n" + after.lstrip()
    if existing.strip():
        return existing.rstrip() + "\n\n" + block
    return block


def ensure_env_example(project_root: pathlib.Path) -> bool:
    env_example = project_root / ".env.example"
    existing = env_example.read_text(encoding="utf-8") if env_example.exists() else ""
    missing = [name for name in WORDPRESS_MCP_ENV if name not in existing]
    if not missing:
        return False
    addition = """

# -----------------------------------------------------------------------------
# WordPress MCP / Novomira (project-local, optional)
# -----------------------------------------------------------------------------
# These are not WordPress REST credentials. They are used only by the local
# .codex/config.toml MCP wrapper for @automattic/mcp-wordpress-remote.
# WP_API_URL=https://example.com/wp-json/mcp/novamira
# WP_API_USERNAME=
# WP_API_PASSWORD=
"""
    write_text(env_example, existing.rstrip() + addition)
    return True


def ensure_gitignore(project_root: pathlib.Path) -> bool:
    gitignore = project_root / ".gitignore"
    existing = gitignore.read_text(encoding="utf-8") if gitignore.exists() else ""
    entries = [".env"]
    changed = False
    lines = set(existing.splitlines())
    new_text = existing.rstrip()
    for entry in entries:
        if entry not in lines:
            new_text += ("\n" if new_text else "") + entry
            changed = True
    if changed:
        write_text(gitignore, new_text + "\n")
    return changed


def build_report(cfg_path: pathlib.Path, write: bool, server_name: str) -> dict[str, Any]:
    cfg = load_yaml(cfg_path)
    project_root = project_root_for(cfg_path)
    local_config = project_root / ".codex" / "config.toml"
    enabled = is_wordpress_project(cfg)
    report: dict[str, Any] = {
        "project_root": str(project_root),
        "config": str(cfg_path),
        "enabled": enabled,
        "server_name": server_name,
        "local_config": str(local_config),
        "env_required": list(WORDPRESS_MCP_ENV),
        "secrets_written": False,
        "status": "skipped_non_wordpress",
    }
    if not enabled:
        return report

    block = managed_block(project_root, server_name)
    existing = local_config.read_text(encoding="utf-8") if local_config.exists() else ""
    rendered = replace_managed_block(existing, block)
    report["status"] = "ready"
    report["changed"] = rendered != existing
    if write:
        write_text(local_config, rendered)
        report["env_example_updated"] = ensure_env_example(project_root)
        report["gitignore_updated"] = ensure_gitignore(project_root)
    return report


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate project-local Codex MCP config.")
    parser.add_argument("config", nargs="?", help="Path to seo-cycle.yaml")
    parser.add_argument("--write", action="store_true", help="Write .codex/config.toml and env hints.")
    parser.add_argument("--server-name", default=DEFAULT_SERVER_NAME)
    parser.add_argument("--format", choices=("json", "text"), default="text")
    args = parser.parse_args()

    cfg_path = pathlib.Path(args.config).expanduser().resolve() if args.config else find_config(pathlib.Path.cwd())
    if not cfg_path or not cfg_path.exists():
        print(f"ERROR: seo-cycle.yaml not found in {pathlib.Path.cwd()}", file=sys.stderr)
        return 2
    report = build_report(cfg_path, args.write, args.server_name)
    if args.format == "json":
        print(json.dumps(report, ensure_ascii=False, indent=2, sort_keys=True))
    else:
        print(f"Project MCP config status: {report['status']}")
        print(f"Local config: {report['local_config']}")
        if report["enabled"]:
            print("Env required: " + ", ".join(report["env_required"]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
